/* Fiche de révision (affichée par #/fiche, imprimable) */
window.FICHE = [
'<div class="f-sec"><h4>MODÈLES OSI / TCP-IP</h4><table>',
'<tr><th>OSI</th><th>PDU</th><th>Équipement / protocoles</th><th>TCP/IP</th></tr>',
'<tr><td>7 Application</td><td rowspan="3">Données</td><td>HTTP, DNS, SMTP, DHCP</td><td rowspan="3">Application</td></tr>',
'<tr><td>6 Présentation</td><td>formats, chiffrement</td></tr><tr><td>5 Session</td><td>sessions</td></tr>',
'<tr><td>4 Transport</td><td>Segment</td><td>TCP (connecté, fiable) / UDP</td><td>Transport</td></tr>',
'<tr><td>3 Réseau</td><td>Paquet</td><td>IP, ICMP — routeur</td><td>Internet</td></tr>',
'<tr><td>2 Liaison</td><td>Trame</td><td>MAC, 802.1Q — switch</td><td rowspan="2">Accès réseau</td></tr>',
'<tr><td>1 Physique</td><td>Bits</td><td>câbles — hub</td></tr></table>',
'Mnémo : <b>P</b>our <b>L</b>e <b>R</b>éseau <b>T</b>out <b>S</b>e <b>P</b>asse <b>A</b>utomatiquement. En-tête IP : 20 o (IHL = 5), TTL, protocole 1 ICMP / 6 TCP / 17 UDP. MTU Ethernet 1500.</div>',

'<div class="f-sec"><h4>PORTS À CONNAÎTRE</h4>HTTP <code>80</code> · HTTPS <code>443</code> · DNS <code>53</code> (UDP, TCP pour transferts de zone) · SMTP <code>25</code> · POP3 <code>110</code> · IMAP <code>143</code> · DHCP <code>67</code> serveur / <code>68</code> client · DHCPv6 <code>547</code>/<code>546</code> · SSH <code>22</code> · Telnet <code>23</code> · FTP <code>20/21</code> · TFTP <code>69</code> · contrôleur SDN PT <code>58000</code></div>',

'<div class="f-sec"><h4>CÂBLES</h4><b>Droit</b> : familles différentes (PC/serveur/routeur ⟷ switch/hub). <b>Croisé</b> : même famille (switch-switch, routeur-routeur, PC-PC, <b>PC-routeur</b>). Console = renversé. Série DCE/DTE entre routeurs (clock rate côté DCE).<br>T568B : bl-or, or, bl-ve, bleu, bl-bleu, ve, bl-ma, ma (A : orange ⟷ vert). UTP (rien), FTP (écran global), STP (par paire). Fibre : <b>monomode</b> 9 µm laser jaune ; <b>multimode</b> 50/62,5 µm LED orange ; ST baïonnette, SC carré, LC petit.</div>',

'<div class="f-sec"><h4>DOMAINES</h4>Hub : 1 domaine de collision pour tout. Switch : 1 domaine de collision <b>par port</b>, 1 seul de diffusion (sauf VLAN). Routeur : coupe la diffusion (1 domaine par interface). Switch : table MAC apprise par l’adresse <b>source</b>, inondation si destination inconnue ou broadcast. Cut-through (rapide) / store-and-forward (vérifie).</div>',

'<div class="f-sec"><h4>IPv4</h4><table><tr><th>Classe</th><th>1er octet</th><th>Masque</th></tr><tr><td>A</td><td>1-126</td><td>/8</td></tr><tr><td>B</td><td>128-191</td><td>/16</td></tr><tr><td>C</td><td>192-223</td><td>/24</td></tr><tr><td>D</td><td>224-239</td><td>multicast</td></tr><tr><td>E</td><td>240-255</td><td>expérimental</td></tr></table>',
'Privées : <code>10/8</code>, <code>172.16/12</code> (→172.31), <code>192.168/16</code>. 127 = loopback, 169.254 = APIPA, 255.255.255.255 = diffusion générale.<br>',
'Octets de masque : 128 192 224 240 248 252 254 255. Hôtes = 2<sup>h</sup> − 2. <b>Réseau = IP ET masque</b>, diffusion = bits hôte à 1. Pas = 256 − octet du masque.</div>',

'<div class="f-sec"><h4>SOUS-RÉSEAUX / VLSM</h4><table><tr><th>/n</th><th>masque</th><th>hôtes</th></tr><tr><td>/24</td><td>.0</td><td>254</td></tr><tr><td>/25</td><td>.128</td><td>126</td></tr><tr><td>/26</td><td>.192</td><td>62</td></tr><tr><td>/27</td><td>.224</td><td>30</td></tr><tr><td>/28</td><td>.240</td><td>14</td></tr><tr><td>/29</td><td>.248</td><td>6</td></tr><tr><td>/30</td><td>.252</td><td>2</td></tr><tr><td>/23</td><td>255.255.254.0</td><td>510</td></tr><tr><td>/20</td><td>255.255.240.0</td><td>4094</td></tr><tr><td>/12</td><td>255.240.0.0</td><td>—</td></tr></table>',
'n sous-réseaux → 2<sup>bits</sup> ≥ n. VLSM : du <b>plus grand au plus petit</b>, sans trou, liaisons /30 à la fin. 15 hôtes → /27 (un /28 = 14). En /23, x.x.4.255 et x.x.5.0 sont des hôtes valides !</div>',

'<div class="f-sec"><h4>ROUTAGE</h4><code>ip route 172.16.3.0 255.255.255.0 172.16.2.2</code> · défaut <code>ip route 0.0.0.0 0.0.0.0 &lt;nh&gt;</code> · <code>show ip route</code><br>Codes : C connecté, L local, S statique, S* défaut, R RIP, O OSPF, D EIGRP. AD : connecté 0, statique 1, EIGRP 90, OSPF 110, RIP 120. <b>Préfixe le plus long</b> gagne.<br>RIP (vecteur de distance, sauts ≤ 15) : <code>router rip</code>, <code>version 2</code>, <code>network &lt;réseau connecté&gt;</code>, <code>no auto-summary</code>. OSPF = état de liens (SPF, coût).<br>Tables DS : connecté → passerelle = interface = IP locale ; PC → <code>0.0.0.0 / 0.0.0.0</code> vers sa passerelle. Couleurs prof : jaune connecté, vert statique, orange défaut.</div>',

'<div class="f-sec"><h4>VLAN</h4>1 VLAN = 1 domaine de diffusion = 1 réseau IP. 802.1Q : tag 4 o, VID 12 bits (4094). Access (1 VLAN, non tagué) / trunk (plusieurs, tagués) ; VLAN natif = 1 (non tagué).<br><code>vlan 20</code> · <code>name ADM</code> · <code>interface range fa0/1-8</code> · <code>switchport mode access</code> · <code>switchport access vlan 20</code> · <code>switchport mode trunk</code> · <code>show vlan brief</code> · <code>show interfaces trunk</code><br>DTP : auto + auto = access ! Router-on-a-stick : <code>int g0/0.10</code> · <code>encapsulation dot1Q 10</code> · <code>ip address …254</code> (+ <code>no shutdown</code> sur la physique).</div>',

'<div class="f-sec"><h4>DHCP</h4>D.O.R.A. : Discover (broadcast) → Offer → Request → ACK. Bail : renouvellement à 50 % puis 87,5 %. Pas de réponse → APIPA 169.254/16.<br>Relais : <code>ip helper-address &lt;serveur&gt;</code> sur l’interface <b>côté clients</b>. Routeur : <code>ip dhcp excluded-address a b</code> · <code>ip dhcp pool LAN</code> · <code>network</code> · <code>default-router</code> · <code>dns-server</code>. PT : Start IP + Maximum Number of Users.</div>',

'<div class="f-sec"><h4>DNS / WEB / MAIL</h4><b>DNS</b> : A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail), NS, SOA, PTR (inverse, <code>1.2.168.192.in-addr.arpa</code>). Client récursif, serveurs itératifs. 13 racines logiques (anycast). Primaire modifiable, secondaires par transfert de zone (TCP).<br><b>HTTP</b> : GET, HEAD, POST, PUT, DELETE ; 200 OK, 301/302 redirection, 304 non modifié, 404, 500. 1.1 = keep-alive + Host obligatoire. HTTPS = HTTP sur TLS (443).<br><b>SMTP</b> : HELO/EHLO, MAIL FROM, RCPT TO, DATA (fin « . »), QUIT ; 220, 250, 354, 221, 550 ; 2xx ok, 3xx attente, 4xx transitoire, 5xx définitif. MUA / MTA / MDA. POP = télécharge, IMAP = reste sur le serveur.</div>',

'<div class="f-sec"><h4>NAT / PAT</h4><code>ip nat inside</code> (LAN) · <code>ip nat outside</code> (Internet) · <code>access-list 1 permit 192.168.1.0 0.0.0.255</code> · <code>ip nat inside source list 1 interface g0/1 overload</code> (PAT) · <code>ip nat inside source static tcp 192.168.2.11 80 13.1.1.2 8000</code> (redirection : local puis global) · <code>show ip nat translations</code>. Inside local = privée, inside global = publique.</div>',

'<div class="f-sec"><h4>IPv6</h4>128 bits, 8 blocs de 16 bits en hexa. Simplifier : zéros de tête, puis <b>un seul</b> « :: ». FE80::/10 lien local (passerelle !), FC00::/7 ULA, 2000::/3 globale, FF00::/8 multicast (FF02::1 nœuds, FF02::2 routeurs), ::1 loopback. Pas de broadcast.<br>EUI-64 : MAC coupée + FFFE + inversion du 7e bit (00→02). NDP : RS/RA, NS/NA (remplace ARP, DAD). SLAAC (M0 O0), + DHCPv6 sans état (O=1 : <code>ipv6 nd other-config-flag</code>), avec état (M=1).<br><code>ipv6 unicast-routing</code> · <code>ipv6 address 2001:db8:1:1::/64 eui-64</code> · <code>ipv6 route ::/0 fc00::2</code>. /48 → 65 536 sous-réseaux /64.</div>',

'<div class="f-sec"><h4>STP / HSRP / SDN</h4><b>STP</b> (802.1D, RSTP 802.1w) : racine = plus petit BID (priorité 32768 + MAC) ; 1 port racine par switch, 1 port désigné par segment, les autres bloqués. Coûts : 10G 2, 1G 4, 100M 19, 10M 100. États : blocage 20 s → écoute 15 s → apprentissage 15 s → acheminement. <code>spanning-tree vlan 1 priority 4096</code>.<br><b>HSRP</b> (Cisco ; VRRP standard ; GLBP charge) : prio 100 par défaut, hello 3 s, hold 10 s, <code>standby 1 ip &lt;vip&gt;</code>, <code>priority 150</code>, <code>preempt</code>, MAC 0000.0c07.acXX. DHCP doit donner l’IP virtuelle.<br><b>SDN</b> : contrôleur central, OpenFlow (ONF), API REST JSON ; POST /api/v1/ticket → 201 ; puis <code>X-Auth-Token</code> ; GET /network-device, /host → 200.</div>',

'<div class="f-sec f-warn"><h4>PIÈGES DU DS</h4>• Correction Excel <b>ligne par ligne</b> : connectés d’abord, dans l’ordre Eth1, Eth2… • Masque 16 sous-réseaux de 10/8 = <code>255.240.0.0</code> ; 4 sous-réseaux d’un /24 = <code>255.255.255.192</code> • Pas de « 01 » dans une adresse • Passerelle = voisin sur la liaison, interface = ta propre IP sur cette liaison • 172.16-31 privé, 172.32 public • PC-routeur = croisé • Router-on-a-stick : switch en trunk + <code>no shutdown</code> + encapsulation avant l’IP • HSRP : IP virtuelle ≠ IP réelles.</div>'
].join('');
