/* Module 1 — questions supplémentaires des niveaux */
(window.EXTRAS = window.EXTRAS || {}).bases = [
  /* ---------- Difficile ---------- */
  { id: 'xb1', lvl: 4, type: 'text', kind: 'num', accept: 0.8, ph: 'secondes',
    q: 'Un fichier de <b>10 Mo</b> (10 millions d’octets) est envoyé sur un lien à <b>100 Mbit/s</b>. Sans compter les en-têtes, la latence ni les pertes, combien de <b>secondes</b> faut-il au minimum ?',
    hints: ['Le débit est en <b>bits</b> par seconde, le fichier en <b>octets</b> : 1 octet = 8 bits.', '10 Mo = 80 Mbit. Durée = quantité ÷ débit.'],
    explain: '10 × 8 = 80 Mbit ; 80 ÷ 100 = <b>0,8 s</b>. En vrai, c’est plus long : surcharge des protocoles (en-têtes, acquittements), encapsulation, latence des équipements, propagation, pertes… exactement la liste « performances » de ton cours.' },
  { id: 'xb2', lvl: 4, type: 'qcm',
    q: 'Un PC crie à tout le réseau « Qui a l’adresse 192.168.1.254 ? » ; seule la machine concernée lui répond, directement à lui. Quels types de communication ?',
    choices: ['Requête en broadcast, réponse en unicast', 'Requête en unicast, réponse en broadcast', 'Les deux en multicast', 'Les deux en broadcast'], good: 0,
    hints: ['La question est entendue par tout le monde ; la réponse n’intéresse qu’une seule machine.'],
    explain: 'C’est ARP : la <b>requête</b> part en <b>broadcast</b> (FF:FF:FF:FF:FF:FF), la <b>réponse</b> revient en <b>unicast</b> vers le demandeur.' },
  { id: 'xb3', lvl: 4, type: 'match', q: 'Associe chaque situation au type de commutation.',
    pairs: [['Un appel téléphonique « à l’ancienne » qui réserve une ligne pendant toute la conversation', 'Commutation de circuits'], ['Un e-mail découpé en datagrammes qui peuvent prendre des chemins différents', 'Commutation de paquets'], ['Une connexion logique établie au début de l’échange, bande passante allouée à la demande', 'Circuit virtuel'], ['Un document entier transmis d’un seul bloc, de nœud en nœud', 'Commutation de messages']],
    hints: ['Réserver une ligne physique = circuit. Découper en datagrammes = paquets.'],
    explain: 'Circuits = liaison réservée (capacité garantie) ; messages = gros blocs ; paquets = datagrammes indépendants (Internet) ; circuit virtuel = connexion logique, bande passante à la demande.' },
  { id: 'xb4', lvl: 4, type: 'text', kind: 'word', accept: ['ID', 'Internet Draft', 'Internet-Draft'], ph: 'Sigle',
    q: 'Avant d’être publié sous forme de RFC, un document de travail de l’IETF s’appelle un… (sigle de 2 lettres)',
    hints: ['« Internet D… » : un brouillon.'],
    explain: 'Un <b>ID</b> (<i>Internet Draft</i>), document de travail. S’il fait consensus, il devient une RFC.' },
  /* ---------- Extrême ---------- */
  { id: 'xb5', lvl: 5, type: 'qcm',
    q: 'Les serveurs racine du DNS sont dupliqués partout dans le monde : un même serveur logique (même adresse IP) existe en des dizaines d’exemplaires, et ta requête arrive au plus proche. De quel type de communication s’agit-il ?',
    choices: ['Unicast', 'Broadcast', 'Multicast', 'Anycast'], good: 3,
    hints: ['Un destinataire parmi un ensemble de cibles possibles…'],
    explain: '<b>Anycast</b> : une adresse, plusieurs machines, on joint la plus proche. Tu le retrouveras au module DNS (serveurs racine) et en IPv6.' },
  { id: 'xb6', lvl: 5, type: 'qcm',
    q: 'Des PC sont câblés en étoile autour d’un <b>concentrateur (hub)</b>. Quelle est la <b>topologie logique</b> ?',
    choices: ['Étoile', 'Bus', 'Anneau', 'Maillée'], good: 1,
    hints: ['Topologie logique = la façon dont circule l’information. Que fait un hub d’un signal reçu ?'],
    explain: 'Physiquement en <b>étoile</b>, mais le hub répète chaque signal sur tous ses ports : logiquement, c’est un <b>bus</b> (tout le monde entend tout).' },
  { id: 'xb7', lvl: 5, type: 'multi',
    q: 'Le même fichier met 2 s à arriver chez A et 5 s chez B, avec le même débit annoncé. D’après ton cours, quelles causes sont possibles chez B ?',
    choices: ['Plus d’équipements traversés (temps de latence)', 'Un réseau plus chargé (surcharge du réseau)', 'Davantage de pertes de paquets, donc de retransmissions', 'Une distance plus grande (temps de propagation)', 'Le fichier est plus gros chez B', 'Les câbles de B sont d’une autre couleur'],
    good: [0, 1, 2, 3],
    hints: ['C’est le même fichier… et la couleur d’un câble n’a jamais ralenti personne.'],
    explain: 'Latence des équipements, architecture (nombre de sauts), surcharge du réseau, propagation, surcharge protocolaire, pertes : tout ça s’ajoute au simple « débit ».' },
  /* ---------- Impossible ---------- */
  { id: 'xb8', lvl: 6, type: 'qcm', q: 'À l’IETF, qui décide si le travail d’un groupe dégage un consensus ?',
    choices: ['L’ISO', 'L’IESG', 'L’IANA', 'Le W3C'], good: 1,
    hints: ['C’est un détail de la slide « L’IETF » de ton cours.'],
    explain: 'L’<b>IESG</b> (Internet Engineering Steering Group) juge le « rough consensus ». L’IANA gère les numéros (adresses, ports), le W3C le Web, l’ISO a publié OSI.' },
  { id: 'xb9', lvl: 6, type: 'qcm',
    q: 'En commutation de <b>circuits</b>, deux personnes au téléphone se taisent pendant 30 secondes. Que devient la capacité réservée pendant ce silence ?',
    choices: ['Elle est libérée pour d’autres communications', 'Elle reste réservée et inutilisée', 'La communication est coupée', 'Elle est partagée en multicast'], good: 1,
    hints: ['Le circuit est établi pour toute la durée de la communication, qu’on parle ou non.'],
    explain: 'Elle reste <b>réservée pour rien</b>. C’est pour ça que la commutation de <b>paquets</b> « utilise mieux les ressources » : sans données, on n’occupe rien.' },
  { id: 'xb10', lvl: 6, type: 'qcm',
    q: 'On remplace le hub par un <b>switch</b> (toujours câblé en étoile). La topologie <b>logique</b> devient…',
    choices: ['Toujours un bus', 'Une étoile : une trame unicast ne part que vers le port du destinataire', 'Un anneau', 'Aucune, le switch n’a pas de topologie'], good: 1,
    hints: ['Le switch lit l’adresse MAC de destination et n’envoie la trame que sur le bon port.'],
    explain: 'Avec un switch, le trafic unicast va de point à point : la topologie logique rejoint la physique (<b>étoile</b>). Seuls les broadcasts continuent d’aller partout.' },
  { id: 'xb11', lvl: 6, type: 'multi', q: 'Parmi ces messages, lesquels sont des <b>broadcasts</b> ?',
    choices: ['La requête ARP « Qui a 192.168.1.1 ? »', 'Le DHCP Discover d’un PC qui démarre', 'La réponse ARP', 'Un ping vers 192.168.1.20', 'Un paquet envoyé à 255.255.255.255', 'Une annonce RIPv2 vers 224.0.0.9'],
    good: [0, 1, 4],
    hints: ['Une réponse est adressée à celui qui a demandé.', '224.0.0.9, c’est une adresse de groupe (classe D).'],
    explain: 'Broadcast : requête ARP, DHCP Discover, 255.255.255.255. La réponse ARP et le ping sont en unicast ; 224.0.0.9 est du <b>multicast</b> (groupe des routeurs RIPv2).' }
];
